### ISSUE TITLE
Decode fragmented request or response

### ISSUE THREAD

**Issue by jfallows** [reaktivity/nukleus-http.java#2]
Decoding an HTTP `BEGIN` frame requires a complete HTTP request or HTTP response, including all headers, even though these may arrive in multiple fragmented `DATA` frames from the underlying transport.

**Comment by jfallows** [comment]
We should consider supporting multiple `BEGIN` frames, with a `FIN` bit set on the last one, where each `BEGIN` frame immediately sends the information it has decoded so far and no `DATA` frames are permitted until after the last `BEGIN` frame (with `FIN` bit set).

In the pessimistic scenario, where the recipient needs to cache all the `BEGIN` frames before processing them as a whole, there is not much benefit compared to caching the raw bytes comprising the entire request (or response), except for a potentially more compact representation in memory.

However, in the optimistic scenario, where only a subset of the observed information is retained by the recipient to apply routing decisions or handshake rules, then significant savings can be observed.

This approach would seem to significantly reduce overall complexity.

Note: HTTP/2 headers follow a similar fragmentation-capable strategy.

**Comment by jfallows** [comment]
In practice, we will still need to decode enough of the request or response to apply any route source matching rules before sending even the first non-`FIN` `BEGIN` frame to the correct target.

**Comment by cmebarrow** [comment]
@jfallows I don't think this is actually a bug. It is more of an enhancement request. PR #9 does handle fragmented requests. The only limitation is that requests whose total headers size exceed the value of system property "nukleus.http.maximum.headers.size" are rejected with a bad request status. This is http spec compliant since that spec allows implementations to impose limits on for example the maximum header size that they support. The enhancement request of course would be to relax this limit and support larger requests.

**Comment by jfallows** [comment]
Agreed @cmebarrow.
